"""Print APP_VERSION, and write the PyInstaller version resource from it.

APP_VERSION in amber_core.py is the single source of truth; build.ps1 uses
this script to stamp the exe and the installer.

Usage:  python tools/make_version_info.py [output-path]
"""
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def app_version() -> str:
    tree = ast.parse((ROOT / "amber_core.py").read_text(encoding="utf-8"))
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
                getattr(t, "id", None) == "APP_VERSION" for t in node.targets):
            return node.value.value
    raise SystemExit("APP_VERSION not found in amber_core.py")


TEMPLATE = """# UTF-8 — generated by tools/make_version_info.py; do not edit.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tup},
    prodvers={tup},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', 'Aldinga Media'),
          StringStruct('FileDescription', 'Amber Price Tray'),
          StringStruct('FileVersion', '{dotted}'),
          StringStruct('InternalName', 'AmberPriceTray'),
          StringStruct('OriginalFilename', 'AmberPriceTray.exe'),
          StringStruct('ProductName', 'Amber Price Tray'),
          StringStruct('ProductVersion', '{dotted}'),
          StringStruct('LegalCopyright', 'Aldinga Media')
        ])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def main() -> None:
    version = app_version()
    parts = [int(p) for p in version.split(".")]
    parts = (parts + [0, 0, 0, 0])[:4]
    if len(sys.argv) > 1:
        Path(sys.argv[1]).write_text(TEMPLATE.format(
            tup=tuple(parts), dotted=".".join(map(str, parts))), encoding="utf-8")
    print(version)


if __name__ == "__main__":
    main()
